# Generated by Django 4.1 on 2022-09-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_id',
            new_name='items',
        ),
    ]
